#         These settings are not secure and are not intended for production use.
#         Please override this configuration when configuring a production instance.

version: '3.2'

services:
  app:
    # "build: ." invokes the Dockerfile in .
    build: .
    container_name: secret-msg
    environment:

      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shhh
      MYSQL_USER: shhh
      MYSQL_PASSWORD: shhh123

      FLASK_ENV: development
      HOST_MYSQL: 127.0.0.1
      DB_MYSQL: shhh
      USER_MYSQL: shhh
      PASS_MYSQL: shhh123

    ports:
      - 5000:5000
    command: /container-bin/container-rc.sh
    volumes:
        - type: bind
          source: "./bin"
          target: "/container-bin"
        - type: bind
          source: "./mysql/initialize.sql"
          target: "/docker-entrypoint-initdb.d/initialize.sql"
#        - type: bind
#          source: "./mysql_data"
#          target: "/var/lib/mysql"

volumes:
  mysql_data:
